export const sampleAnalysis = {
  primary_symbol: "XAUUSD",
  secondary_symbol: "XAGUSD",
  execution_timeframe: "M15",
  context_timeframes: ["H4", "H1", "D1"],
  analysis_as_of: "2026-05-16T13:30:00Z",
  rule_version: "mvp-0.1",
  market_state: "post_sweep_displacement",
  active_model: "IRL_TO_ERL_BEARISH",
  bias: "SELL",
  action: "WAIT",
  data_coverage: {
    status: "complete",
    missing: [],
    stale: [],
    degraded_mode: false,
    last_candles: {
      XAUUSD_M15: "2026-05-16T13:30:00Z",
      XAGUSD_M15: "2026-05-16T13:30:00Z",
      XAUUSD_H1: "2026-05-16T13:00:00Z",
      XAUUSD_H4: "2026-05-16T12:00:00Z",
      XAUUSD_D1: "2026-05-16T00:00:00Z",
    },
  },
  time_context: {
    session: "New York",
    killzone: true,
    valid_time: true,
  },
  htf_context: {
    bias_source: "H4 dealing range with H1 confirmation",
    dealing_range_high: 2435.2,
    dealing_range_low: 2388.1,
    equilibrium: 2411.65,
    current_price: 2400.8,
    current_position: "premium",
    dol_direction: "sellside",
    hrlr_lrlr: {
      status: "hrlr_to_lrlr",
      hrlr_taken: true,
      hrlr_direction: "buyside",
      hrlr_price: 2432.1,
      target_direction: "sellside",
      target_lrlr: {
        direction: "sellside",
        price: 2390,
        swing_count: 2,
      },
    },
    mmxm_swing_grade: {
      status: "complete",
      model: "MMSM",
      direction: "sellside",
      phase: "premium_distribution",
      quadrant: 0.75,
      fib_position: 0.73,
      terminus_price: 2388.1,
      terminus_side: "sellside",
      range_timeframe: "H4",
    },
    judas_swing: {
      status: "judas_confirmed",
      detected: true,
      session: "New York",
      manipulation_direction: "buyside",
      target_direction: "sellside",
      opening_range_high: 2432.1,
      opening_range_low: 2390,
      judas_price: 2435.2,
      target_price: 2390,
      alignment: "aligned",
      confidence: "high",
    },
  },
  liquidity: {
    recently_taken: [
      {
        label: "internal_buyside_liquidity",
        timeframe: "M15",
        price: 2432.1,
      },
    ],
    next_dol: {
      label: "previous_day_low",
      timeframe: "D1",
      liquidity_type: "ERL",
      direction: "sellside",
      price: 2390,
      score: 82,
      confidence: "high",
      reasoning: [
        "HTF price is trading in premium",
        "Internal buyside liquidity was swept on M15",
        "Bearish SSMT appeared between XAUUSD and XAGUSD",
        "Previous day low is the strongest external sellside pool",
      ],
    },
  },
  dol_candidates: [
    {
      label: "previous_day_low",
      timeframe: "D1",
      liquidity_type: "ERL",
      direction: "sellside",
      price: 2390,
      score: 82,
      confidence: "high",
    },
    {
      label: "h4_internal_swing_low",
      timeframe: "H4",
      liquidity_type: "IRL",
      direction: "sellside",
      price: 2399.4,
      score: 68,
      confidence: "medium",
    },
  ],
  ssmt: {
    available: true,
    detected: true,
    type: "bearish",
    quality: "high",
    sync_status: "aligned",
    sequence: "sequential",
    reference_quarter: "2026-05-16Q2",
    primary_quarter: "2026-05-16Q3",
    magneto: false,
    magneto_level: 2390,
  },
  confirmation: {
    sweep: true,
    displacement: true,
    mss: false,
    fvg: true,
  },
  trade_idea: {
    action: "WAIT",
    reason_code: "MISSING_MSS",
    blocking_conditions: ["mss"],
    gate_status: "blocked",
    reason_wait:
      "Bearish HTF and M15 sweep are aligned, but MSS confirmation is missing.",
    entry_model: null,
    entry_area: null,
    stop_loss: null,
    take_profit: 2390,
    invalidation: "MSS required before entry model becomes valid",
  },
  gate_result: {
    passed: false,
    failed_reasons: ["MISSING_MSS"],
    required_confirmations: ["sweep", "displacement", "mss", "fvg"],
    present_confirmations: ["sweep", "displacement", "fvg"],
  },
  confidence: "medium",
  reasoning: [
    "HTF price is trading in premium.",
    "HTF DOL points toward external sellside liquidity.",
    "M15 swept internal buyside liquidity.",
    "Bearish SSMT detected between XAUUSD and XAGUSD.",
    "MSS has not confirmed, so action remains WAIT.",
  ],
  narrative:
    "The selected DOL is previous_day_low because HTF context is premium and the M15 move swept buyside liquidity with bearish SSMT and displacement. The trade idea remains WAIT with reason code MISSING_MSS until bearish market structure confirms.",
  warnings: [],
};

export const analyzeRequest = {
  primary_symbol: "XAUUSD",
  secondary_symbol: "XAGUSD",
  execution_timeframe: "M15",
  context_timeframes: ["H4", "H1", "D1"],
  analysis_as_of: "2026-05-16T13:30:00Z",
  mode: "normal",
};
