from __future__ import annotations

from enum import StrEnum


class Action(StrEnum):
    WAIT = "WAIT"
    BUY = "BUY"
    SELL = "SELL"


class ReasonCode(StrEnum):
    MISSING_HTF_CONTEXT = "MISSING_HTF_CONTEXT"
    NO_ACTIVE_DEALING_RANGE = "NO_ACTIVE_DEALING_RANGE"
    UNCLEAR_DOL = "UNCLEAR_DOL"
    DOL_AMBIGUOUS = "DOL_AMBIGUOUS"
    HTF_CONFLICT = "HTF_CONFLICT"
    HTF_M15_CONFLICT = "HTF_M15_CONFLICT"
    MISSING_SWEEP = "MISSING_SWEEP"
    MISSING_SSMT = "MISSING_SSMT"
    SSMT_UNAVAILABLE = "SSMT_UNAVAILABLE"
    MISSING_DISPLACEMENT = "MISSING_DISPLACEMENT"
    MISSING_MSS = "MISSING_MSS"
    MISSING_FVG = "MISSING_FVG"
    MISSING_INVALIDATION = "MISSING_INVALIDATION"
    STALE_DATA = "STALE_DATA"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    GATE_COMPLETE = "GATE_COMPLETE"
